spring:
  application:
    name: products-service

  data:
    redis:
      port: 6379
      host: localhost
      username: default
      password: Develop3r

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    io:
      lettuce:
        core: debug