spring:
  application:
    name: products-service

  profiles:
    active: local

  data:
    redis:
      port: 6379
      host: localhost
      username: default
      password: Develop3r
      replica-group-id: ""

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    org:
      springframework:
        data:
          redis: trace
    io:
      lettuce:
        core: trace
